warnings_are_errors: false
language: node_js
node_js:
  - "8.12"
script: 
  - echo "Deploying to firebase"
  - npm i
  - npm run build
install:
  - npm i -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive