language: node_js
node_js:
  - "8.12"
script: 
  - npm i
  - CI=false 
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && npm run build
install:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && npm i -g firebase-tools
after_success:
  - itest $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && firebase deploy --token "$FIREBASE_TOKEN"